### ISSUE TITLE
Update JWT lib to latest version (v2)

### ISSUE THREAD

**Issue by gbrlsnchs** [ironsmile/euterpe#27]
Hi there! I was checking which libs use the JWT library I have created and found your project. I like it very much, congrats. But I advise you to update my lib to version 2 since there are some performance enhancements. However, code is not backwards compatible, so you might need to make some adjustments in order to make it work, but it's definitely worth it.

Anyway, thanks for your trust in my work.

**Comment by ironsmile** [comment]
Thanks, I will check it out! It might take some time till I get around to doing it, though. My pace on this project is measured, to say the least.
