### ISSUE TITLE
Default listen address for docker

### ISSUE THREAD

**Issue by EYHN** [ironsmile/euterpe#28]
I tried to install euterpe use docker, by following command.

```
docker build -t ironsmile/euterpe github.com/ironsmile/euterpe
```

but I cannot access from the host. I found that the default listening address of the server is `localhost:9996`, and you need to manually change it to `0.0.0.0:9996`. 

For out-of-the-box use, can you change the default listening address in docker to `0.0.0.0:9996`.

Also if you can publish docker image to dockerhub, that would be great.

**Comment by ironsmile** [comment]
Yea, you are right. I've missed how changing the default address to `localhost` would affect the Docker image.

**Comment by ironsmile** [comment]
Done, it should be fixed on the latest `master`. And there's Euterpe at the Docker Hub: https://hub.docker.com/r/ironsmile/euterpe
Will automate pushing new images soon too.
