### ISSUE TITLE
Set loop or random by default

### ISSUE THREAD

**Issue by martadinata666** [ironsmile/euterpe#48]
Can we set loop or random enabled by default? Im looking the config example but can find anything, thanks 🌷

**Comment by ironsmile** [comment]
Hey! No, currently there is not configuration option. My plan is to make it so that the options are remembered in the browser. So if one sets their "loop" option to true then it will stay true every time they refresh the page. Do you think this will be enough?

**Comment by martadinata666** [comment]
imo that should be enough, and i agree with any implementation you want to use, per local browser settings or system wide, or both `system wide settings that can be override locally`

**Comment by ironsmile** [comment]
Done in [v1.5.3](https://github.com/ironsmile/euterpe/releases/tag/v1.5.3).
