### ISSUE TITLE
error while loading libtag_c.so.0

### ISSUE THREAD

**Issue by 5calV** [ironsmile/euterpe#55]
Using https://github.com/ironsmile/euterpe/releases/download/v1.5.4/euterpe_v1.5.4_linux_amd64.tar.gz on Debian 12.
After downloading the tar.gz, executing "INSTALL". Then I wanted to do the first run by typing "euterpe", but I get following error:
"error while loading libtag_c.so.0: cannot open shared object file: No such file or directory"

Any way to fix this?
I have been following these Instructions:
https://github.com/ironsmile/euterpe/tree/v1.5.4

**Comment by ironsmile** [comment]
Hello! As far as I could tell you need to install the `taglib` package:

```sh
sudo apt-get install taglib
```

That should be all!

**Comment by 5calV** [comment]
looks like this package is not in debian's repositories, at least not under this name.

**Comment by Alex-Smith-1234** [comment]
sudo apt-get install libtagc0 libtagc0-dev
