### ISSUE TITLE
[Feature request]: Avoid resampling: play bit perfect audio

### ISSUE THREAD

**Issue by marek-lach** [ironsmile/euterpe#57]
Since I have a lossless music collection consisting of FLACs, I would appreciate the option to avoid any system resampling by euterpe and with an uncapped bit rate to be able to play bit-perfect audio.

Thank you for considering.

**Comment by ironsmile** [comment]
Hello, @marek-lach ! I am unaware of any resampling done to FLAC files. So as far as I know what you are asking is already the case. Or am I missing something? Can you explain a bit more how you know that resampling is happening.

**Comment by marek-lach** [comment]
> Hello, @marek-lach ! I am unaware of any resampling done to FLAC files. So as far as I know what you are asking is already the case. Or am I missing something? Can you explain a bit more how you know that resampling is happening.

Good to know! I wasn't sure, as there is no bitrate information in the web interface:

![Screenshot from 2024-05-19 18-23-32](https://github.com/ironsmile/euterpe/assets/45913977/c9aad4c1-ae35-4a92-aec2-970163a7a779)

Will close this now.
